#!/usr/bin/env python3
"""The artifacts collection page, generated from the folders beside it.

Each folder under artifacts/ is one published page: its own index.html, with a
<title> and a <meta name="description">, and whatever files it loads. The
collection page, artifacts/index.html, lists every folder by name with that
title and description, and nothing else, so it can neither promise a page that
is not there nor miss one that is.

    python3 scripts/artifacts_index.py          write artifacts/index.html
    python3 scripts/artifacts_index.py --check  red if the committed page is stale
"""

from __future__ import annotations

import html
import sys
from dataclasses import dataclass
from html.parser import HTMLParser
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent / "artifacts"


class Refused(Exception):
    """A folder that cannot be listed: no page, no title or no description."""


@dataclass(frozen=True)
class Entry:
    folder: str
    title: str
    description: str


class _Head(HTMLParser):
    def __init__(self) -> None:
        super().__init__()
        self.title = ""
        self.description: str | None = None
        self._in_title = False

    def handle_starttag(self, tag: str, attrs: list[tuple[str, str | None]]) -> None:
        a = dict(attrs)
        if tag == "title":
            self._in_title = True
        elif tag == "meta" and a.get("name") == "description":
            self.description = a.get("content") or ""

    def handle_endtag(self, tag: str) -> None:
        if tag == "title":
            self._in_title = False

    def handle_data(self, data: str) -> None:
        if self._in_title:
            self.title += data


def entries(root: Path) -> list[Entry]:
    """Every folder under root, by name; a folder that cannot be listed is refused."""
    found = []
    for folder in sorted(p for p in root.iterdir() if p.is_dir()):
        page = folder / "index.html"
        if not page.is_file():
            raise Refused(f"{folder.name}/index.html is missing")
        head = _Head()
        head.feed(page.read_text(encoding="utf-8"))
        title = " ".join(head.title.split())
        if not title:
            raise Refused(f"{folder.name}/index.html has no title")
        if not head.description:
            raise Refused(f"{folder.name}/index.html has no description")
        found.append(Entry(folder.name, title, " ".join(head.description.split())))
    return found


def render(listed: list[Entry]) -> str:
    items = "\n".join(
        f'      <li><a href="{html.escape(e.folder)}/">{html.escape(e.title)}</a>'
        f"<p>{html.escape(e.description)}</p></li>"
        for e in listed
    )
    return f"""<!doctype html>
<!-- GENERATED by scripts/artifacts_index.py from the folders beside it: do not hand-edit. -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Artifacts · vista-forge</title>
<meta name="description" content="Standalone pages published by the vista-forge project.">
<style>
  :root {{ --bg: #f5f7fa; --surface: #ffffff; --ink: #15202b; --ink2: #526070; --line: #d8dee6; --accent: #1766d6; color-scheme: light; }}
  @media (prefers-color-scheme: dark) {{
    :root {{ --bg: #0e141a; --surface: #151c24; --ink: #e4eaf1; --ink2: #a0acb9; --line: #28333f; --accent: #7cb0ff; color-scheme: dark; }}
  }}
  body {{ margin: 0; background: var(--bg); color: var(--ink); font: 17px/1.6 system-ui, -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; padding: 48px 16px 64px; }}
  main {{ max-width: 760px; margin: 0 auto; display: grid; gap: 18px; }}
  a {{ color: var(--accent); text-underline-offset: 3px; }}
  .home {{ margin: 0; font-size: 0.9rem; }}
  h1 {{ margin: 0; font-size: 2.4rem; line-height: 1.1; }}
  .intro {{ margin: 0; color: var(--ink2); }}
  ul {{ list-style: none; margin: 8px 0 0; padding: 0; display: grid; gap: 12px; }}
  li {{ background: var(--surface); border: 1px solid var(--line); border-radius: 12px; padding: 16px 18px; }}
  li a {{ font-size: 1.2rem; font-weight: 700; text-decoration: none; }}
  li a:hover, li a:focus-visible {{ text-decoration: underline; }}
  li p {{ margin: 4px 0 0; color: var(--ink2); }}
</style>
</head>
<body>
  <main>
    <p class="home"><a href="../">vista-forge</a></p>
    <h1>Artifacts</h1>
    <p class="intro">Standalone pages from the vista-forge project. Each is self-contained and opens on its own.</p>
    <ul>
{items}
    </ul>
  </main>
</body>
</html>
"""


def check(root: Path) -> list[str]:
    """What is wrong with the committed collection page; empty when it is current."""
    index = root / "index.html"
    if not index.is_file():
        return ["artifacts/index.html is missing: run `make artifacts` and commit it"]
    if index.read_text(encoding="utf-8") != render(entries(root)):
        return ["artifacts/index.html is stale: run `make artifacts` and commit it"]
    return []


def _folders(n: int) -> str:
    return f"{n} folder" if n == 1 else f"{n} folders"


def main(argv: list[str]) -> int:
    try:
        if "--check" in argv:
            problems = check(ROOT)
            for p in problems:
                print(f"artifacts-check: {p}", file=sys.stderr)
            if not problems:
                print(f"artifacts-check: artifacts/index.html lists all {_folders(len(entries(ROOT)))}")
            return 1 if problems else 0
        (ROOT / "index.html").write_text(render(entries(ROOT)), encoding="utf-8")
        print(f"artifacts: wrote artifacts/index.html ({_folders(len(entries(ROOT)))})")
        return 0
    except Refused as e:
        print(f"artifacts: {e}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
